llm_model: gemma3:1b
embedding_model: nomic-embed-text:latest
vector_db_path: rag/data/vector_db
top_k_retrieval: 6
max_iterations: 3
chunk_size: 1000
chunk_overlap: 200
semgrep_config: "rules/custom-flask-vulns.yaml"
code_path: "rag/data/sources"